### ISSUE TITLE
Email address not correctly assigned

### ISSUE THREAD

**Issue by NiklasVin** [scientificcomputing/fenics2024#6]
I noticed that my email address was assigned to a different author of the abstract. If it were possible, I would be grateful if you'd change the author section of this [abstract](https://github.com/scientificcomputing/fenics2024/blob/9a0b4e5d089e9400d62487c030dbebf25fbc453d/book/abstracts/higher-order-time.md), to:
```diff
  - name: Prof. Dr. Hans-Joachim Bungartz
    affiliation: Technical University of Munich
-    email: niklas.vinnitchenko@tum.de
+    email: bungartz@cit.tum.de
  - name: Prof. Dr. Benjamin Uekermann
    affiliations: University of Stuttgart
+    email: benjamin.uekermann@ipvs.uni-stuttgart.de
  - name: M.Sc. (hons) Benjamin Rodenberg
    affiliations: Technical University of Munich
+    email: benjamin.rodenberg@cit.tum.de
  - name: Niklas Vinnitchenko
    affiliations: Technical University of Munich
+    email: niklas.vinnitchenko@tum.de
```
Thank you, and sorry for any inconvenience.

**Comment by jorgensd** [comment]
Sorry for the mistake, here is the updated version: https://scientificcomputing.github.io/fenics2024/higher-order-time
